<a href="https://colab.research.google.com/github/nandithashetty/Applications-of-Python-Programming-in-DA-and-ML/blob/master/Day3PandasAndNumpyExamples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PANDAS EXAMPLES**

1.Write a Pandas program to convert a Panda module Series to Python list and its type.

In [1]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


2.Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [2]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


3.Write a Pandas program to compare the elements of the two Pandas Series.

Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [3]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


4.Write a Pandas program to convert a dictionary to a Pandas series.

Sample dictionary: d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}

In [4]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


5.Write a Pandas program to convert a NumPy array to a Pandas series.

Sample NumPy array: d1 = [10, 20, 30, 40, 50]

In [5]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


6.Write a Pandas program to change the data type of the given Series into numeric

['100', '200', 'python', '300.12', '400']

In [6]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


7.Write a Pandas program to convert a given Series to an array.

In [7]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


8.Write a Pandas program to sort a given Series.

In [8]:
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


9.Write a Pandas program to add some data to an existing Series.

In [9]:
import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


10.Write a Pandas program to create a subset of a given series based on value and condition.

In [10]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


11.Write a Pandas program to change the order of index of a given series.

In [11]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


12.Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

In [12]:
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


13.Write a Pandas program to get the elements of an array values into column-wise.

Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

In [13]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [16]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [17]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [19]:
#2.1 Get the file
downloaded = drive.CreateFile({'id':'1cWYo3L6Tdwnsuy04CzgbGNrisJy3TFaB'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv') 

In [20]:
import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))

   adult  ... vote_count
0  False  ...     5415.0

[1 rows x 24 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


14.Write a Pandas program to get the columns of the DataFrame (movies_metadata.csv file).

In [21]:
import pandas as pd
import numpy as np
df = pd.read_csv('movies_metadata.csv')
print("Columns of the DataFrame:")
print(df.columns)

Columns of the DataFrame:
Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


15.Write a Pandas program to get the details of the thrid movie of the DataFrame #(movie_metadata.csv file).

In [22]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
third_movie = df.iloc[2]
print("Details of the third moviee:")
print(third_movie)

Details of the third moviee:
adult                                                                False
belongs_to_collection    {'id': 119050, 'name': 'Grumpy Old Men Collect...
budget                                                                   0
genres                   [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...
homepage                                                               NaN
id                                                                   15602
imdb_id                                                          tt0113228
original_language                                                       en
original_title                                            Grumpier Old Men
overview                 A family wedding reignites the ancient feud be...
popularity                                                         11.7129
poster_path                               /6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
production_companies     [{'name': 'Warner Bros.', 'id': 6194}, {'name'

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


16.Write a Pandas program to display the first 10 rows of the DataFrame.

In [23]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df.head(10)
print("First 10 rows of the DataFrame:")
print(result)


First 10 rows of the DataFrame:
   adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0
2  False  ...       92.0
3  False  ...       34.0
4  False  ...      173.0
5  False  ...     1886.0
6  False  ...      141.0
7  False  ...       45.0
8  False  ...      174.0
9  False  ...     1194.0

[10 rows x 24 columns]


/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


**NUMPY EXAMPLES**

17.Write a NumPy program to generate five random numbers from the normal distribution.

In [24]:
import numpy as np
x = np.random.normal(size=5)
print(x)

[ 0.81188524 -0.33947057  0.05327698  1.43593861  1.57669361]


18.Write a NumPy program to generate six random integers between 10 and 30

In [25]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)

[12 22 26 18 16 14]


19.Write a NumPy program to create a 3x3x3 array with random values.

In [26]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.91002166 0.82223575 0.45263282]
  [0.11573637 0.75512888 0.2044265 ]
  [0.37763263 0.14019177 0.5762819 ]]

 [[0.33812472 0.0688032  0.3984477 ]
  [0.49527446 0.31649376 0.40658516]
  [0.40498664 0.69023525 0.63942765]]

 [[0.89603922 0.77106462 0.44909761]
  [0.99398952 0.47476467 0.63842917]
  [0.1834822  0.93735381 0.49372611]]]


20.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [27]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.52370216 0.53403737 0.96145549 0.61926858 0.18233017]
 [0.95814449 0.33957077 0.77491285 0.67576766 0.92216371]
 [0.17275301 0.47658482 0.37495056 0.18966111 0.02029728]
 [0.70725881 0.07852741 0.0218569  0.98495335 0.79051702]
 [0.71472087 0.77346605 0.30256128 0.869419   0.36128531]]
Minimum and Maximum Values:
0.02029728496507699 0.9849533468646923


21.Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [28]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)

Original array: 
[[0.27960391 0.25626011 0.64685569 0.66926776]
 [0.44878432 0.45861176 0.32155166 0.57514626]
 [0.49222475 0.36663116 0.34285498 0.04335997]
 [0.27727419 0.74027462 0.14917677 0.56246071]
 [0.14616428 0.99783824 0.16980528 0.47362255]
 [0.40314231 0.69752271 0.66085428 0.57992139]
 [0.82400037 0.51527677 0.76248479 0.26685351]
 [0.67119088 0.16960664 0.57383163 0.62432518]
 [0.87654447 0.90515392 0.8442552  0.58898278]
 [0.90972918 0.40611401 0.82723025 0.79040774]]
First 5 rows of the above array:
[[0.27960391 0.25626011 0.64685569 0.66926776]
 [0.44878432 0.45861176 0.32155166 0.57514626]
 [0.49222475 0.36663116 0.34285498 0.04335997]
 [0.27727419 0.74027462 0.14917677 0.56246071]
 [0.14616428 0.99783824 0.16980528 0.47362255]]
First 3 columns of the above array:
[[0.27960391 0.25626011 0.64685569 0.66926776]
 [0.44878432 0.45861176 0.32155166 0.57514626]
 [0.49222475 0.36663116 0.34285498 0.04335997]
 [0.27727419 0.74027462 0.14917677 0.56246071]
 [0.14616428 0.9978

22.Write a NumPy program to shuffle numbers and find permutation between 0 and 10 (inclusive).

In [29]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[9 4 1 3 6 5 2 0 7 8]
Same result using permutation():
[2 1 9 5 4 8 7 6 0 3]


23.Write a NumPy program to create a random integer nos of size 10 and sort it.

In [30]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.59380386 0.51340717 0.48678476 0.6845929  0.20976728 0.82555798
 0.98178657 0.32321117 0.10509613 0.37067408]
Sorted array:
[0.10509613 0.20976728 0.32321117 0.37067408 0.48678476 0.51340717
 0.59380386 0.6845929  0.82555798 0.98178657]


24.Write a NumPy program to create a random integer nos of size 10 and sort it.

In [31]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)

[5 9 7 6 8 2 1 0 4 3]
[0 1 2 3 4 5 6 7 8 9]
